name: Reddit Bot

on:
  schedule:
    - cron: '*/30 * * * *'  # every 30 mins, or whatever schedule you want
  workflow_dispatch:        # enables manual run button

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Reddit Bot
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            python reddit_bot.py manual
          else
            python reddit_bot.py
          fi
